### PR TITLE
Use the latest version of ckanserviceprovider

### LINKED ISSUE #124: Flask exception with latest CKAN master
When I install datapusher onto CKAN (master) (which now has Flask dependency) CKAN does not start and commands all have this error:
```
(default)vagrant@vagrant-ubuntu-trusty-64:/vagrant/src/pgl_test$ paster --plugin ckan db init
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 239, in command
    self._load_config(cmd!='upgrade')
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 178, in _load_config
    conf = self._get_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 175, in _get_config
    return appconfig('config:' + self.filename)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 261, in appconfig
    global_conf=global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 454, in get_context
    section)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 646, in find_egg_entry_point
    possible.append((entry.load(), protocol, entry.name))
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2203, in load
    return self.resolve()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2209, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 10, in <module>
    from ckan.config.middleware.flask_app import make_flask_stack
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 9, in <module>
    from flask.ctx import _AppCtxGlobals
ImportError: cannot import name _AppCtxGlobals
```

This problem is caused by installing an older version of Flask than latest CKAN requires.
Installing ckan-service-provider (for datapusher) downgrades Flask from 0.11.1 to 0.9.

The fix is to reinstall the correct version for CKAN:
    pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt
However I've not looked yet at what effect this has on datapusher.

### PR DESCRIPTION
**Pull request by davidread**
This provides this fix: https://github.com/ckan/ckan-service-provider/pull/32
so that datapusher works with CKAN 2.7.

Fixes #124

### CODE REVIEW

**Comment by davidread** [comment]
@klikstermkd could you test this, so that it can be merged?

**Comment by klikstermkd** [comment]
Yes, now it works properly.

**Comment by davidread** [comment]
@amercader would you merge?

**Comment by amercader** [comment]
I released 0.0.12 after merging this

**Comment by davidread** [comment]
Thanks!!
